### ISSUE TITLE
"InAppBrowser" plugin is not implemented on ios

### ISSUE THREAD

**Issue by kamrankamrani** [ionic-team/capacitor-os-inappbrowser#27]
I am facing this issue. Any ideas?

```
"@capacitor/core": "^6.0.0"
"@capacitor/inappbrowser": "^1.0.1"
"@capacitor/ios": "^6.0.0"
```

I did following steps:

```
npm install @capacitor/inappbrowser
npx cap sync
```
<img width="526" alt="Screenshot 2024-10-02 at 09 23 06" src="https://github.com/user-attachments/assets/b860c3c2-71f8-4dfe-851d-79780c1ac970">

```
<ion-button onClick={this.handleClick}>Test</ion-button>
```

```
private handleClick = () => {
    InAppBrowser.openInWebView({
      url: 'https://www.google.com',
      options: DefaultWebViewOptions,
    });
  };
```

**Comment by poulainpi** [comment]
I'm experiencing the same problem—the plugin isn't recognized at all when running npx cap sync. I've tried several plugins, and this is the only one that isn't recognized. Another odd aspect is the plugin's version, 1.0.2, which doesn't follow the same versioning pattern as other Capacitor plugins. Could this be the reason it's not recognized?

**Comment by kamrankamrani** [comment]
@poulainpi same for me. There is a `example-app` folder inside the repo. I tried to run that app but I will get this error:

```
Error:   Failed to scan for dependencies from entries:
  /Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/index.html

  ✘ [ERROR] Failed to resolve entry for package "@capacitor/inappbrowser". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/esbuild/lib/main.js:1225:21:
      1225 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46541:15)
    at resolvePackageEntry (file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46538:3)
    at tryNodeResolve (file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46354:16)
    at ResolveIdContext.resolveId (file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46104:19)
    at PluginContainer.resolveId (file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48919:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49530:22)
    at async file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49692:28
    at async requestCallbacks.on-resolve (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:1225:22)
    at async handleRequest (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:647:11)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49680:13)
    at handlePlugins (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:699:5)
    at /Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:2032:27)
    at Object.context (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:1874:58)
    at prepareEsbuildScanner (file:///Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49477:24)

  The plugin "vite:dep-scan" was triggered by this import

    src/pages/Home.tsx:2:206:
      2 │ ...ndroidViewStyle, AndroidAnimation } from '@capacitor/inappbrowser';
        ╵                                             ~~~~~~~~~~~~~~~~~~~~~~~~~


    at failureErrorWithLog (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:1315:45)
    at buildResponseToResult (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:943:7)
    at /Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:955:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:954:54)
    at handleRequest (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:647:17)
    at handleIncomingPacket (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:672:7)
    at Socket.readFromStdout (/Users/kamran/Work/capacitor-os-inappbrowser-dev/example-app/node_modules/esbuild/lib/main.js:600:7)
```

I ran `npm install` in root file. Am I missing something here?

**Comment by poulainpi** [comment]
I identified the issue as being caused by the following configuration in the package.json of the plugin:
```json
"exports": {
  ".": {
    "types": "./dist/index.d.ts",
    "import": "./dist/plugin.mjs",
    "require": "./dist/plugin.cjs"
  }
}
```
This setup was causing the plugin discovery to fail.
Upgrading from @capacitor/cli 6.1.1 to 6.2.0 resolved the problem

**Comment by claytonjack** [comment]
Seems like this is an issue again. When running @capacitor/cli 7.0.1 and @capacitor/inappbrowser 2.0.0 (the most recent version of both) the plugin still isn't being recognized by npx cap sync. Any ideas?

**Comment by OS-pedrogustavobilro** [comment]
Hey everyone, FYI, `package.json` is now also exported in version 2.3.1, so this issue should be fixed.
