### ISSUE TITLE
[Bug] Android App crashing after adding this plugin

### ISSUE THREAD

**Issue by Harshida-ck** [ionic-team/capacitor-os-inappbrowser#30]
changed the minsdkVersion from 22 to 26.Build the app and deployed.

After adding this plugin, application crashes while opening.

This is the link of my sample source code: [https://github.com/Harshida-ck/Capacitor-Angular-App](url)

**Comment by patforg** [comment]
Getting the same problem...

Install via  `yarn add @capacitor/inappbrowser`

When I try and launch my application I get this exception

```
FATAL EXCEPTION: main
Process: com.example.app, PID: 6677
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
    at android.app.ActivityThread.installProvider(ActivityThread.java:7770)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983)
    at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
        at android.app.ActivityThread.main(ActivityThread.java:8177)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
    Caused by: androidx.startup.StartupException: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7765)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:205) 
        at android.os.Looper.loop(Looper.java:294) 
        at android.app.ActivityThread.main(ActivityThread.java:8177) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
    Caused by: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:173)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2619) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2589) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7765) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:205) 
        at android.os.Looper.loop(Looper.java:294) 
        at android.app.ActivityThread.main(ActivityThread.java:8177) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
        at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:37)
        at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:25)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:173) 
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2619) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2589) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7765) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:205) 
        at android.os.Looper.loop(Looper.java:294) 
        at android.app.ActivityThread.main(ActivityThread.java:8177) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ReportFragment$ActivityInitializationListener" on path: DexPathList[[zip file "/data/app/~~NLz6pVkxL_BG26CfBYB_3Q==/com.danslescoulisses.app-od1eX8Gb4XCbNwKGnXVSNw==/base.apk"],nativeLibraryDirectories=[/data/app/~~NLz6pVkxL_BG26CfBYB_3Q==/com.danslescoulisses.app-od1eX8Gb4XCbNwKGnXVSNw==/lib/x86_64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:37) 
        at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:25) 
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180) 
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:173) 
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2619) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2589) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7765) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:205) 
        at android.os.Looper.loop(Looper.java:294) 
        at android.app.ActivityThread.main(ActivityThread.java:8177) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by patforg** [comment]
I was able to get the plugin working by upgrading to a newer Gradle version

I changed it in the file `android\gradle\wrapper\gradle-wrapper.properties`

changed the line with `distributionUrl` to 

```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-bin.zip
```

**Comment by MarcelSchuermann** [comment]
I have the same issue.
Related issue #33 and Ionic post:
[https://forum.ionicframework.com/t/capacitor-inappbrowser-crashes-app-on-android/245034/3](https://forum.ionicframework.com/t/capacitor-inappbrowser-crashes-app-on-android/245034/3)

**Comment by ItsSkynet** [comment]
can confirm that new release 1.0.3 fixes this issue, tested as well in web compilers like Monaca.io

**Comment by broomfn** [comment]
> can confirm that new release 1.0.3 fixes this issue, tested as well in web compilers like Monaca.io

Not for me it doesn't still getting the same errors as mentioned above 🤷

**Comment by kamrankamrani** [comment]
If it is possible for your project, upgrade AGP version. At least 8.5.0 as it is in the `example-app` of this repo. But I'm working with AGP `8.8.0` with version `2.0.0` of this package and it is working fine.

**Comment by OS-pedrogustavobilro** [comment]
I think this no longer happens in the latest plugin version, if you could try updating to that version and try again.

**Comment by OS-pedrogustavobilro** [comment]
Closing this issue because it does not happen with the latest version of the plugin.

If you're still facing this problem please open a new issue with as much info as possible.

Thank you!

**Comment by ngdevc** [comment]
This error occurs again between capacitor v8 and  @capacitor/inappbrowser v 3.0.3.

**Comment by OS-pedrogustavobilro** [comment]
@ngdevc can you provide more information on the error, does it only occur on release builds, or does it also occur on debug builds? Also are you able to share a sample application that reproduces the crash? I recommend opening a new issue with as much information as possible for the team to analyze it.

Thank you!

**Comment by ngdevc** [comment]
@OS-pedrogustavobilro 
This error has been solved by this modification.

<img width="786" height="245" alt="Image" src="https://github.com/user-attachments/assets/79fdfa8d-d84c-4332-8f92-1909899e1933" />
